//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1057 with alias "headingAndSubheading"
	/// <summary>Heading And Subheading</summary>
	public partial interface IHeadingAndSubheading : IPublishedContent
	{
		/// <summary>Heading</summary>
		string Heading { get; }

		/// <summary>Subheading</summary>
		string Subheading { get; }
	}

	/// <summary>Heading And Subheading</summary>
	[PublishedContentModel("headingAndSubheading")]
	public partial class HeadingAndSubheading : PublishedContentModel, IHeadingAndSubheading
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "headingAndSubheading";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeadingAndSubheading(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeadingAndSubheading, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Heading: The main heading for the page
		///</summary>
		[ImplementPropertyType("heading")]
		public string Heading
		{
			get { return GetHeading(this); }
		}

		/// <summary>Static getter for Heading</summary>
		public static string GetHeading(IHeadingAndSubheading that) { return that.GetPropertyValue<string>("heading"); }

		///<summary>
		/// Subheading: The subheading to appear beneath the main page heading
		///</summary>
		[ImplementPropertyType("subheading")]
		public string Subheading
		{
			get { return GetSubheading(this); }
		}

		/// <summary>Static getter for Subheading</summary>
		public static string GetSubheading(IHeadingAndSubheading that) { return that.GetPropertyValue<string>("subheading"); }
	}
}
